### ISSUE TITLE
argument must be a string a bytes-like object or a number not 'tensor' 

### ISSUE THREAD

**Issue by hilaPollak** [taipingeric/yolo-v4-tf.keras#2]
Hi, I run the model and get error:
"argument must be a string a bytes-like object or a number not 'tensor' "
in the file: tensor_shape.py line 193 in __init__
what could be the problem?
My custom have 4 classes and wasn't be- trained

**Comment by nasheedyasin** [comment]
Have you retrained the model for your 4 custom classes?
