### ISSUE TITLE
Freezing Layers for transfer learning

### ISSUE THREAD

**Issue by nasheedyasin** [taipingeric/yolo-v4-tf.keras#4]
Hi I intend to use the pre-trained darknet weights to train my own model, is such training possible in the current setup?

I found that you load the weights here:
in Yolov4.build_model()
```
 def build_model(self, load_pretrained=True):
      if load_pretrained and self.weight_path and self.weight_path.endswith('.weights'):
          if self.weight_path.endswith('.weights'):
              load_weights(self.yolo_model, self.weight_path)
              print(f'load from {self.weight_path}')
          elif self.weight_path.endswith('.h5'):
              self.training_model.load_weights(self.weight_path)
              print(f'load from {self.weight_path}')
```

As such I found no way to freeze layers in your current code.

**Comment by taipingeric** [comment]
you can freeze layers by yolo_model

```python
for layer in model.yolo_model.layers[:LAYER_YOU_WANT]:
    layers.trainable = False
````

**Comment by WujuMaster** [comment]
@nasheedyasin Hi sir, I'm experimenting with transfer learning with the pretrained weights too, can you give me some advice on how can I figure out which layers I need to freeze? Thank you
