### ISSUE TITLE
Can't load custom model properly

### ISSUE THREAD

**Issue by Miremax** [taipingeric/yolo-v4-tf.keras#9]
Good afternoon :)
I train model like You said in train.ipynb. Then predict, it predicts well:
> img shape:  (324, 432, 3) # of bboxes: 2

Then I save the model: _model.save_model('auto_model3.h5')_
And when I load it back by _model = Yolov4(weight_path='auto_model3.h5', class_name_path=class_name_path)_ , it does not predict at all! Doesn't show any boxes. I can't understand why and what am I doing wrong: 
> img shape:  (324, 432, 3) # of bboxes: 0

Model size is ok: auto_model3.h5 - 251 181 KB

Any advice? Or can You show the code, when You train the model. then save it, then loads back and it works?
Thank You in advance ))

**Comment by gajdosech2** [comment]
Hello there, a similar issue was closed recently https://github.com/taipingeric/yolo-v4-tf.keras/issues/8. To sum it up, you should use method `load_model`. You just create instance of `Yolov4` and call that method on the instance, as can be seen in this script in my fork of this repo https://github.com/gajdosech2/yolo-v4-tf.keras/blob/master/inference.py. From the code https://github.com/taipingeric/yolo-v4-tf.keras/blob/23f89c7c3734db81aa3bc62fefae73ad0d9353d6/utils.py#L12  it seems that the _weight_path_ parameter in the constructor serves only to load the official YOLO pretrained weights from the darknet backend [github/AlexeyAB/darknet](https://drive.google.com/open?id=1cewMfusmPjYWbrnuJRuKhPMwRe_b9PaT), i.e, not your custom ones trained here.

**Comment by Miremax** [comment]
Oh, it really worked) 
Seems, we have to initialize model to be a Yolov4 model first, and only then call it's method load_model, not original tf.keras.models.load_model .
Thank you)
